format_version: v1.0
type: UniqueComponent
attributes: {id: adc}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: AD1CON1__ASAM}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: AD1CON1__CLRASAM}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: KeyValueSet
    attributes: {id: AD1CON1__SSRC}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '3'}
  - type: Boolean
    attributes: {id: AD1CON2__CSCNA}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: KeyValueSet
    attributes: {id: AD1CON2__SMPI}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '6'}
  - type: Integer
    attributes: {id: AD1CON3__ADCS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Hex
    attributes: {id: ADC_AD1CHS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc, value: '0'}
  - type: Hex
    attributes: {id: ADC_AD1CON1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc, value: '224'}
  - type: Hex
    attributes: {id: ADC_AD1CON2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc, value: '24'}
  - type: Hex
    attributes: {id: ADC_AD1CON3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc, value: '7938'}
  - type: Hex
    attributes: {id: ADC_AD1CSSL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc, value: '0'}
  - type: Boolean
    attributes: {id: ADC_INTERRUPT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Float
    attributes: {id: ADC_TCLK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc, value: '75.0'}
- type: ElementPosition
  attributes: {x: '326', y: '222', id: adc}
