files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/32mxSom
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: 829F8E2841B0FD41BF448C59678B13D0
  logicalPath: config/32mxSom
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 829F8E2841B0FD41BF448C59678B13D0
- generatedChecksum: 60C42001D22A692995B1E49DD4649AB6
  logicalPath: config/32mxSom
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: EF5145E09D945A9671D528E80DC92272
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 1DDB7FD746F67B5787750C1046CFC61F
  logicalPath: config/32mxSom/peripheral/adc
  name: plib_adc.c
  physicalPath: peripheral/adc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1DDB7FD746F67B5787750C1046CFC61F
- generatedChecksum: 2F8D2F5AE2544E2AAB9FD3A1345E08B8
  logicalPath: config/32mxSom/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2F8D2F5AE2544E2AAB9FD3A1345E08B8
- generatedChecksum: 290F2AF9D54789315ECA75CF8107FC69
  logicalPath: config/32mxSom/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 290F2AF9D54789315ECA75CF8107FC69
- generatedChecksum: 4C3296DD82515A0C1F3538B4369876E3
  logicalPath: config/32mxSom/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4C3296DD82515A0C1F3538B4369876E3
- generatedChecksum: 3D25431D6E746DF7A51F3271572A009E
  logicalPath: config/32mxSom/peripheral/i2c/master
  name: plib_i2c2_master.c
  physicalPath: peripheral/i2c/master
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3D25431D6E746DF7A51F3271572A009E
- generatedChecksum: 9CF277BD1BA6EF54EDB0EFCF8BB9190F
  logicalPath: config/32mxSom/peripheral/spi/spi_master
  name: plib_spi3_master.c
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9CF277BD1BA6EF54EDB0EFCF8BB9190F
- generatedChecksum: 6F4C9D4939F4A3EE54AC2991DDF84071
  logicalPath: config/32mxSom/peripheral/tmr
  name: plib_tmr2.c
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6F4C9D4939F4A3EE54AC2991DDF84071
- generatedChecksum: D29D84714DAB5A2427E0E0B16E3770F0
  logicalPath: config/32mxSom/peripheral/tmr
  name: plib_tmr3.c
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: D29D84714DAB5A2427E0E0B16E3770F0
- generatedChecksum: B266FBB29A59D5A6B5F267FA6EC0B8AA
  logicalPath: config/32mxSom/peripheral/tmr
  name: plib_tmr4.c
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: B266FBB29A59D5A6B5F267FA6EC0B8AA
- generatedChecksum: 32751579F2290967C37F7525B965DB53
  logicalPath: config/32mxSom/peripheral/tmr
  name: plib_tmr5.c
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: 32751579F2290967C37F7525B965DB53
- generatedChecksum: 4BA8E99244FBF6D7D3D9B31A9DC699F0
  logicalPath: config/32mxSom/peripheral/uart
  name: plib_uart2.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4BA8E99244FBF6D7D3D9B31A9DC699F0
- generatedChecksum: 9AD9499126403BCD1BC9A3BFA752CB5E
  logicalPath: config/32mxSom/peripheral/uart
  name: plib_uart5.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9AD9499126403BCD1BC9A3BFA752CB5E
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/32mxSom/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: 548B16913AFFD2EC15C6A64B28F2DB53
  logicalPath: config/32mxSom
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 548B16913AFFD2EC15C6A64B28F2DB53
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/32mxSom
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/32mxSom
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: E8917BB734DC71DCEBD331F58F060D11
  logicalPath: config/32mxSom/peripheral/adc
  name: plib_adc.h
  physicalPath: peripheral/adc
  security: NON_SECURE
  type: HEADER
  userChecksum: E8917BB734DC71DCEBD331F58F060D11
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/32mxSom/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: F569C9EC24DC21EDF38E97CDF3A5F97E
  logicalPath: config/32mxSom/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: F569C9EC24DC21EDF38E97CDF3A5F97E
- generatedChecksum: F1232606A2B80FE8B22E597BBC836E8E
  logicalPath: config/32mxSom/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: F1232606A2B80FE8B22E597BBC836E8E
- generatedChecksum: 092C94C5559AFFB03C3483EE129E0E91
  logicalPath: config/32mxSom/peripheral/i2c/master
  name: plib_i2c2_master.h
  physicalPath: peripheral/i2c/master
  security: NON_SECURE
  type: HEADER
  userChecksum: 092C94C5559AFFB03C3483EE129E0E91
- generatedChecksum: B963C6FE44292A1C4A14C3BA5BE95AEE
  logicalPath: config/32mxSom/peripheral/i2c/master
  name: plib_i2c_master_common.h
  physicalPath: peripheral/i2c/master
  security: NON_SECURE
  type: HEADER
  userChecksum: B963C6FE44292A1C4A14C3BA5BE95AEE
- generatedChecksum: 8F2E844DA6CAA767345FCCE94FA28735
  logicalPath: config/32mxSom/peripheral/spi/spi_master
  name: plib_spi3_master.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: 8F2E844DA6CAA767345FCCE94FA28735
- generatedChecksum: CFA758C8B7258190473EF7C60C4BA4E9
  logicalPath: config/32mxSom/peripheral/spi/spi_master
  name: plib_spi_master_common.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: CFA758C8B7258190473EF7C60C4BA4E9
- generatedChecksum: 612994C7F3C27F2CFA2621C1F65D4068
  logicalPath: config/32mxSom/peripheral/tmr
  name: plib_tmr2.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: 612994C7F3C27F2CFA2621C1F65D4068
- generatedChecksum: AB441E032FD7B269DB6B2AA5661A890C
  logicalPath: config/32mxSom/peripheral/tmr
  name: plib_tmr3.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: AB441E032FD7B269DB6B2AA5661A890C
- generatedChecksum: AD9A7F1EF04DC1CC99D6B688E9248227
  logicalPath: config/32mxSom/peripheral/tmr
  name: plib_tmr4.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: AD9A7F1EF04DC1CC99D6B688E9248227
- generatedChecksum: 10F3D2095F245631617CC4D28D83A2C0
  logicalPath: config/32mxSom/peripheral/tmr
  name: plib_tmr5.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: 10F3D2095F245631617CC4D28D83A2C0
- generatedChecksum: D948F2CE092CAB556EF299D3CCD83A55
  logicalPath: config/32mxSom/peripheral/tmr
  name: plib_tmr_common.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: D948F2CE092CAB556EF299D3CCD83A55
- generatedChecksum: 2EFB3352DACC0BD3AA78FE3A976A039E
  logicalPath: config/32mxSom/peripheral/uart
  name: plib_uart2.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 2EFB3352DACC0BD3AA78FE3A976A039E
- generatedChecksum: 75A95547460DD5F9EA4790FA4B3E4D54
  logicalPath: config/32mxSom/peripheral/uart
  name: plib_uart5.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 75A95547460DD5F9EA4790FA4B3E4D54
- generatedChecksum: 91611515A95D92B82B7F4064C16D122B
  logicalPath: config/32mxSom/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 91611515A95D92B82B7F4064C16D122B
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config/32mxSom
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: 08F2FE68EE259663A7283810FD5278BF
  logicalPath: config/32mxSom
  name: p32MX795F512L.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 08F2FE68EE259663A7283810FD5278BF
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/32mxSom;../src/packs/PIC32MX795F512L_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '1024'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/32mxSom;../src/packs/PIC32MX795F512L_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
