configName: 32mxSom
folderName: Som795
format_version: v1.0
frameworkPath: ../../HarmonyFramework
processor: PIC32MX795F512L
projectName: Som795
settings:
  PackageFilter: crypto;net;core;bootloader_apps_usb;x2c;bootloader_apps_sdcard;bootloader_apps_uart;bootloader;net_apps_pic32mx;bsp;quick_docs;usb;bootloader_apps_ethernet;csp;MPLAB-Harmony-Reference-Apps;micrium_ucos3;core_apps_pic32mx;bootloader_apps_i2c;csp_apps_pic32mx
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: ./dev_packs/arm/CMSIS/5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: ./dev_packs/Microchip/PIC32MX_DFP/1.5.259/atdf/PIC32MX795F512L.atdf
