format_version: v1.0
type: UniqueComponent
attributes: {id: spi3}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: SPI_BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi3, value: '39'}
  - type: Comment
    attributes: {id: SPI_CLOCK_MODE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '***SPI Mode 0 is Selected***'}
  - type: Hex
    attributes: {id: SPI_DUMMY_DATA}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '255'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi3, value: '255'}
  - type: Boolean
    attributes: {id: SPI_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: SPI_SPICON_CLK_PH}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: KeyValueSet
    attributes: {id: SPI_SPICON_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '3'}
  - type: KeyValueSet
    attributes: {id: SPI_SPICON_MSSEN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
- type: ElementPosition
  attributes: {x: '329', y: '474', id: spi3}
